[package]
name = "day_08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "day_08_lib"
path = "src/lib.rs"

[[bin]]
name = "day_08"
path = "src/main.rs"

[dependencies]
